import './app';
// constants
import './constants/baseUrl.constant';
import './constants/lang.constant';
// services
import './services/facebook.service';
import './services/formValidation.service';
// directives
import './directives/selectBox.directive';
import './directives/imageFromSVG.directive';
// components
import './components/navBar.component';